# Use the official MariaDB image
FROM mariadb:latest

# Set environment variables
ENV MARIADB_ROOT_PASSWORD 2NUW-a5QdH-8fAXy
ENV MARIADB_DATABASE adatbazis

# Expose port 3306 for connection from the Flask app
EXPOSE 3306
